### ISSUE TITLE
RuntimeError: Model parameter did not receive gradient: encoder.embed_tokens.weight. Use the param in the forward pass or set requires_grad=False

### ISSUE THREAD

**Issue by BUAAers** [wangqiangneu/dlcl#3]
@wangqiangneu 学长您好，我请教您一个问题。我在使用train-wmt-en2de-deep-prenorm-dlcl.sh进行训练时，会出现下面这个问题。按照错误提示我在_forward()里没有找到在哪里改正，也没见requires_grad在哪里，所以请问我需要怎么设置才能正常训练呢？

Traceback (most recent call last):
  File "/home/zwc/python-virtual-environments/dlcl-master/multiprocessing_train.py", line 46, in run
    single_process_main(args)
  File "/home/zwc/python-virtual-environments/dlcl-master/train.py", line 126, in main
    train(args, trainer, task, epoch_itr)
  File "/home/zwc/python-virtual-environments/dlcl-master/train.py", line 172, in train
    log_output = trainer.train_step(sample, update_params=True)
  File "/home/zwc/python-virtual-environments/dlcl-master/fairseq/trainer.py", line 152, in train_step
    grad_norm = self._all_reduce_and_rescale(grad_denom)
  File "/home/zwc/python-virtual-environments/dlcl-master/fairseq/trainer.py", line 228, in _all_reduce_and_rescale
    flat_grads = self._flat_grads = self._get_flat_grads(self._flat_grads)
  File "/home/zwc/python-virtual-environments/dlcl-master/fairseq/trainer.py", line 253, in _get_flat_grads
    grads = self._get_grads()
  File "/home/zwc/python-virtual-environments/dlcl-master/fairseq/trainer.py", line 247, in _get_grads
    raise RuntimeError('Model parameter did not receive gradient: ' + name + '. '
RuntimeError: Model parameter did not receive gradient: encoder.embed_tokens.weight. Use the param in the forward pass or set requires_grad=False

**Comment by BUAAers** [comment]
学长，我知道了。我把sh中的配置改一下就好了。batch_size之前是4096，我的机器不能满足运行条件所以报出一些错误，设置小一点就没问题了。（我的智商真是堪忧啊）

    batch_size=128
    # accumulate gradient (equivalent to 4096 * 2 token batch size per GPU)
    update_freq=64

**Comment by wangqiangneu** [comment]
> 学长，我知道了。我把sh中的配置改一下就好了。batch_size之前是4096，我的机器不能满足运行条件所以报出一些错误，设置小一点就没问题了。（我的智商真是堪忧啊）
> 
> ```
> batch_size=128
> # accumulate gradient (equivalent to 4096 * 2 token batch size per GPU)
> update_freq=64
> ```

解决了就好，那我close了哈 :)
